version: "3.7"
services:
    micro_02:
        build:
            args:
                user: thiago
                uid: 1000
            context: ./
            dockerfile: DockerFile
        image: laravel-app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            -   ./:/var/www
        networks:
            - microservices02

    queue:
        build:
            args:
                user: thiago
                uid: 1000
            context: ./
            dockerfile: DockerFile
        command:
            - php
            - artisan
            - queue:work
        restart: unless-stopped
        volumes:
            - ./:/var/www
        depends_on:
            - redis
        networks:
            - microservices02
    nginx:
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - 8001:80
        volumes:
            -   ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks:
            - microservices02
    db_micro_02:
        image: mysql:5.7.22
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
        volumes:
            - ./.docker/mysql/dbdata:/var/lib/mysql
        ports:
            - 3309:3306
        networks:
            - microservices02
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        restart: unless-stopped
        environment:
            PMA_HOST: db_micro_02
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        ports:
            - 8282:80
        networks:
            - microservices02
    redis:
        image: redis:latest
        ports:
            - 6379:6379
        networks:
            - microservices02
networks:
    microservices02:
        driver: bridge
